import "server-only";
import { AiError, aiReady, geminiJson } from "../ai/gemini";
import { SEGMENTS } from "../plans";
import { AI_BOTS } from "./crawl";
import type { AiOutput, GscData, Issue, PageResult, SiteInfo, SpeedResult } from "./types";

type Biz = { name: string; segment: string; city: string | null; goal: string | null; audience: string | null; offer: string | null; voice: string | null; website: string | null };

const segLabel = (id: string) => SEGMENTS.find((s) => s.id === id)?.label ?? id;
const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);
const pathOf = (u: string) => { try { return new URL(u).pathname; } catch { return u; } };

/* ───────── Deterministic files (always valid) ───────── */

export function buildRobots(site: SiteInfo) {
  // Keep the site's own Disallow rules for everyone, allow search + AI crawlers, list the sitemap.
  const own = (site.robots.text ?? "").split(/\r?\n/);
  const disallows: string[] = [];
  let inStar = false;
  for (const raw of own) {
    const l = raw.replace(/#.*/, "").trim();
    if (/^user-agent\s*:/i.test(l)) inStar = /:\s*\*\s*$/.test(l);
    else if (inStar && /^disallow\s*:\s*\S/i.test(l) && !/^disallow\s*:\s*\/\s*$/i.test(l)) disallows.push(`Disallow: ${l.split(":").slice(1).join(":").trim()}`);
  }
  const lines = ["# robots.txt — generated by Growvia", "# Lets search engines and AI assistants read your public pages.", "", "User-agent: *", "Allow: /", ...disallows, ""];
  for (const b of AI_BOTS.filter((x) => x.name !== "Googlebot" && x.name !== "Bingbot")) lines.push(`# ${b.owner} — ${b.purpose}`, `User-agent: ${b.name}`, "Allow: /", ...disallows, "");
  const sm = site.robots.sitemaps.length ? site.robots.sitemaps : site.sitemap.url ? [site.sitemap.url] : [`${site.origin}/sitemap.xml`];
  sm.forEach((s) => lines.push(`Sitemap: ${s}`));
  return lines.join("\n") + "\n";
}

export function buildLlmsTxt(b: Biz, site: SiteInfo, pages: PageResult[], summary?: string, facts?: string[]) {
  const ok = pages.filter((p) => p.status === 200 && p.html && !p.noindex && p.title);
  const home = ok[0];
  const intro = summary || home?.description || `${b.name} is a ${segLabel(b.segment).toLowerCase()}${b.city ? ` in ${b.city}` : ""}.${b.offer ? ` ${b.offer}` : ""}`;
  const groups: Record<string, PageResult[]> = { "Main pages": [], "Services & products": [], "Articles & guides": [], "Company": [] };
  for (const p of ok.slice(0, 40)) {
    const path = pathOf(p.url).toLowerCase();
    const g = /blog|news|article|guide|post|insight|resource/.test(path) ? "Articles & guides" : /about|team|contact|career|press|privacy|terms/.test(path) ? "Company" : /service|product|shop|menu|pricing|plan|solution|treatment|course/.test(path) ? "Services & products" : "Main pages";
    groups[g].push(p);
  }
  const out = [`# ${b.name}`, "", `> ${clip(intro.replace(/\s+/g, " "), 400)}`, ""];
  if (facts?.length) { out.push(...facts.slice(0, 8).map((f) => `- ${f}`), ""); }
  for (const [g, ps] of Object.entries(groups)) {
    if (!ps.length) continue;
    out.push(`## ${g}`, "");
    ps.forEach((p) => out.push(`- [${clip(p.title!, 90)}](${p.url})${p.description ? `: ${clip(p.description, 160)}` : ""}`));
    out.push("");
  }
  out.push("## Optional", "", `- [Sitemap](${site.sitemap.url ?? `${site.origin}/sitemap.xml`})`, "");
  return out.join("\n");
}

export function buildSchema(b: Biz, site: SiteInfo, description: string, faq: { q: string; a: string }[]) {
  const type = { restaurant: "Restaurant", dentist: "Dentist", salon: "BeautySalon", gym: "ExerciseGym", realestate: "RealEstateAgent", clinic: "MedicalClinic", lawyer: "LegalService", ecommerce: "OnlineStore" }[b.segment] ?? (["Local business"].includes(SEGMENTS.find((s) => s.id === b.segment)?.group ?? "") ? "LocalBusiness" : "Organization");
  const graph: Record<string, unknown>[] = [
    { "@type": type, "@id": `${site.origin}/#business`, name: b.name, url: site.origin + "/", description, ...(b.city ? { address: { "@type": "PostalAddress", addressLocality: b.city }, areaServed: b.city } : {}) },
    { "@type": "WebSite", "@id": `${site.origin}/#website`, url: site.origin + "/", name: b.name, publisher: { "@id": `${site.origin}/#business` } },
  ];
  if (faq.length) graph.push({ "@type": "FAQPage", mainEntity: faq.slice(0, 8).map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) });
  return JSON.stringify({ "@context": "https://schema.org", "@graph": graph }, null, 2);
}

/* ───────── Rule-based plan (used when AI is off or fails) ───────── */

function rulesOutput(b: Biz, site: SiteInfo, pages: PageResult[], issues: Issue[], gsc: GscData | null): AiOutput {
  const seg = segLabel(b.segment);
  const city = b.city ?? "";
  const crit = issues.filter((i) => i.severity === "critical");
  const warn = issues.filter((i) => i.severity === "warning");
  const note = issues.filter((i) => i.severity === "notice");
  const toItem = (i: Issue) => ({ task: i.title, why: i.fix, impact: (i.severity === "critical" ? "high" : i.severity === "warning" ? "medium" : "low") as "high" | "medium" | "low", effort: (["broken-links", "thin", "js-only", "no-about"].includes(i.id) ? "medium" : "low") as "low" | "medium" | "high" });
  const striking = (gsc?.queries ?? []).filter((q) => q.position >= 4 && q.position <= 20 && q.impressions >= 20).slice(0, 8);
  const faq = [
    { q: `What does ${b.name} offer?`, a: b.offer || `${b.name} is a ${seg.toLowerCase()}${city ? ` in ${city}` : ""}. Get in touch to see how we can help.` },
    ...(city ? [{ q: `Where is ${b.name} located?`, a: `We're based in ${city}. See our Contact page for directions and opening hours.` }] : []),
    { q: `How do I contact ${b.name}?`, a: `Use the contact form on our website, call us, or message us on WhatsApp — we usually reply within a few hours.` },
  ];
  const ok = pages.filter((p) => p.status === 200 && p.html && !p.noindex);
  return {
    source: "rules",
    at: new Date().toISOString(),
    summary: `${site.crawled} pages checked. ${crit.length} critical, ${warn.length} important and ${note.length} minor issues. Fix the critical ones first — they stop pages from being found or trusted.`,
    plan: [
      { phase: "This week — fix what blocks you", items: crit.concat(warn.filter((i) => i.category === "technical")).slice(0, 7).map(toItem) },
      { phase: "This month — pages & AI readiness", items: warn.filter((i) => i.category !== "technical").concat(note.filter((i) => i.category === "ai")).slice(0, 7).map(toItem) },
      { phase: "Next 60 days — grow content", items: [
        ...striking.slice(0, 3).map((q) => ({ task: `Push “${q.key}” onto page 1`, why: `You're at position ${q.position.toFixed(1)} with ${q.impressions} impressions — improve the page that ranks and add internal links to it.`, impact: "high" as const, effort: "medium" as const })),
        { task: `Publish 2 helpful articles a month for ${seg.toLowerCase()} customers${city ? ` in ${city}` : ""}`, why: "Answer real questions in depth; these pages get quoted by AI assistants and bring steady traffic.", impact: "high" as const, effort: "medium" as const },
        { task: "Collect Google reviews every week", why: "Reviews are a top local ranking factor and are read by AI assistants.", impact: "high" as const, effort: "low" as const },
        ...note.filter((i) => i.category !== "ai").slice(0, 3).map(toItem),
      ] },
    ].filter((p) => p.items.length),
    quickWins: issues.filter((i) => ["no-description", "title-length", "no-llms", "no-org-schema", "sitemap-not-in-robots", "no-og", "img-alt", "no-robots"].includes(i.id)).map((i) => `${i.title} — ${i.fix}`).slice(0, 6),
    pageFixes: ok.filter((p) => !p.title || !p.description || p.title.length > 65 || p.title.length < 25 || (p.description?.length ?? 0) < 70).slice(0, 15).map((p) => {
      const topic = p.h1[0] || p.title || pathOf(p.url).split("/").filter(Boolean).pop()?.replace(/[-_]/g, " ") || b.name;
      return { url: p.url, title: clip(`${topic}${city && !topic.includes(city) ? ` in ${city}` : ""} | ${b.name}`, 60), description: clip(`${topic} from ${b.name}${city ? `, ${city}` : ""}. ${b.offer ?? "Get in touch today."}`, 155) };
    }),
    keywords: [
      ...striking.map((q) => ({ keyword: q.key, intent: "already ranking", page: "", note: `position ${q.position.toFixed(1)}, ${q.impressions} impressions` })),
      ...[`${seg.toLowerCase()} ${city}`.trim(), `best ${seg.toLowerCase()}${city ? ` in ${city}` : ""}`, `${seg.toLowerCase()} near me`, `${b.name}`].map((k) => ({ keyword: k, intent: k === b.name ? "brand" : "local", page: site.origin + "/" })),
    ].slice(0, 12),
    contentIdeas: [
      { title: `How to choose the right ${seg.toLowerCase()}${city ? ` in ${city}` : ""}`, type: "Guide", target: `best ${seg.toLowerCase()}${city ? ` ${city}` : ""}`, outline: ["What to look for", "Questions to ask", "Prices to expect", `Why customers pick ${b.name}`] },
      { title: `${b.name} FAQ`, type: "FAQ page", target: `${b.name} questions`, outline: faq.map((f) => f.q) },
    ],
    llmsTxt: buildLlmsTxt(b, site, pages),
    robotsTxt: buildRobots(site),
    schema: buildSchema(b, site, b.offer || pages[0]?.description || `${b.name} — ${seg}${city ? ` in ${city}` : ""}`, faq),
    faq,
  };
}

/* ───────── AI (Gemini) ───────── */

type PlanReply = Pick<AiOutput, "summary" | "plan" | "quickWins" | "keywords" | "contentIdeas" | "faq"> & { siteSummary?: string; keyFacts?: string[]; businessDescription?: string };
type FixReply = { pageFixes: AiOutput["pageFixes"] };

export async function generateSeoAi(b: Biz, site: SiteInfo, pages: PageResult[], issues: Issue[], speed: { mobile?: SpeedResult; desktop?: SpeedResult }, gsc: GscData | null): Promise<AiOutput> {
  const base = rulesOutput(b, site, pages, issues, gsc);
  if (!aiReady) return { ...base, error: "AI is off — add a free GEMINI_API_KEY in Vercel for a smarter plan. This plan was built from the audit rules." };
  const ok = pages.filter((p) => p.status === 200 && p.html).slice(0, 20);
  const context = {
    business: { name: b.name, type: segLabel(b.segment), city: b.city, goal: b.goal, idealCustomers: b.audience, offer: b.offer, brandVoice: b.voice, website: site.origin },
    audit: {
      pagesChecked: site.crawled, https: site.https, sitemap: site.sitemap.found, llmsTxt: site.llms.found,
      aiCrawlersBlocked: site.aiBots.filter((x) => !x.allowed).map((x) => x.name),
      issues: issues.slice(0, 30).map((i) => ({ severity: i.severity, area: i.category, issue: i.title, affectedPages: i.pages?.length ?? 0 })),
      speed: { mobile: speed.mobile?.performance, desktop: speed.desktop?.performance, mobileLcpMs: speed.mobile?.lab?.lcp },
    },
    pages: ok.map((p) => ({ url: p.url, title: p.title, description: p.description, h1: p.h1[0] ?? null, h2: p.h2.slice(0, 6), words: p.words })),
    searchConsole: gsc ? { last28days: gsc.totals, topQueries: gsc.queries.slice(0, 40), topPages: gsc.pages.slice(0, 15) } : null,
  };
  const rules = `You are a senior SEO and GEO (generative-engine optimization: ChatGPT, Perplexity, Google AI Overviews, Claude) consultant. Write in plain, friendly English for a busy business owner — no jargon without a short explanation. Be specific to THIS business and site; use the real page URLs given. Never invent facts (prices, awards, addresses) that aren't in the data — use placeholders like [phone] instead. Return ONLY JSON.`;
  const planPrompt = `${rules}

DATA:
${JSON.stringify(context)}

Return JSON exactly in this shape:
{
 "summary": "3-4 sentences: where the site stands, the biggest problem, the biggest opportunity",
 "plan": [ {"phase":"This week — …","items":[{"task":"…","why":"… (why it matters + how, 1-2 sentences)","impact":"high|medium|low","effort":"low|medium|high"}]}, {"phase":"This month — …","items":[…]}, {"phase":"Next 60 days — …","items":[…]} ],
 "quickWins": ["5-6 fixes doable in under an hour each"],
 "keywords": [ {"keyword":"…","intent":"local|informational|commercial|brand","page":"the URL that should rank (existing URL or 'new page')","note":"why / current position if known"} ]  (10-15, realistic for a business of this size${gsc ? ", prioritise Search Console queries in positions 4-20" : ""}),
 "contentIdeas": [ {"title":"…","type":"Guide|FAQ page|Service page|Comparison|Case study|Local page","target":"main keyword","outline":["H2 …","H2 …","H2 …","H2 …"]} ] (5),
 "faq": [ {"q":"a real question customers ask","a":"a helpful 1-3 sentence answer using only known facts"} ] (6),
 "siteSummary": "2 sentences describing the business for AI assistants (for llms.txt)",
 "keyFacts": ["4-6 short factual bullets about the business for llms.txt, from the data only"],
 "businessDescription": "1 sentence for structured data"
}`;
  const fixPrompt = `${rules}

Rewrite the title tag and meta description for each page below so it ranks and gets clicks. Titles 45-60 characters, include the main topic and ${b.city ? `the city (${b.city}) where natural and ` : ""}the brand at the end. Descriptions 130-155 characters with a clear benefit and call to action. Also suggest an H1 when the current one is missing or weak.
BUSINESS: ${JSON.stringify(context.business)}
PAGES: ${JSON.stringify(ok.slice(0, 15).map((p) => ({ url: p.url, title: p.title, description: p.description, h1: p.h1[0] ?? null, h2: p.h2.slice(0, 4) })))}
Return JSON: {"pageFixes":[{"url":"exact url from the list","title":"…","description":"…","h1":"…"}]}`;
  try {
    const [plan, fixes] = await Promise.all([
      geminiJson<PlanReply>(planPrompt, { temperature: 0.5 }),
      geminiJson<FixReply>(fixPrompt, { temperature: 0.4 }).catch(() => null),
    ]);
    const p = plan.data;
    const faq = Array.isArray(p.faq) && p.faq.length ? p.faq.filter((f) => f?.q && f?.a).slice(0, 8) : base.faq;
    const urls = new Set(ok.map((x) => x.url));
    const pageFixes = (fixes?.data.pageFixes ?? []).filter((f) => f && urls.has(f.url) && f.title).map((f) => ({ url: f.url, title: clip(f.title, 70), description: clip(f.description ?? "", 170), h1: f.h1 }));
    return {
      source: "gemini",
      model: plan.model,
      at: new Date().toISOString(),
      summary: p.summary || base.summary,
      plan: Array.isArray(p.plan) && p.plan.length ? p.plan.filter((x) => x?.phase && Array.isArray(x.items)).map((x) => ({ phase: x.phase, items: x.items.filter((i) => i?.task).slice(0, 8) })) : base.plan,
      quickWins: Array.isArray(p.quickWins) && p.quickWins.length ? p.quickWins.slice(0, 8) : base.quickWins,
      pageFixes: pageFixes.length ? pageFixes : base.pageFixes,
      keywords: Array.isArray(p.keywords) && p.keywords.length ? p.keywords.filter((k) => k?.keyword).slice(0, 20) : base.keywords,
      contentIdeas: Array.isArray(p.contentIdeas) && p.contentIdeas.length ? p.contentIdeas.filter((c) => c?.title).slice(0, 8).map((c) => ({ ...c, outline: Array.isArray(c.outline) ? c.outline : [] })) : base.contentIdeas,
      llmsTxt: buildLlmsTxt(b, site, pages, p.siteSummary, Array.isArray(p.keyFacts) ? p.keyFacts : undefined),
      robotsTxt: base.robotsTxt,
      schema: buildSchema(b, site, p.businessDescription || b.offer || `${b.name}`, faq),
      faq,
    };
  } catch (e) {
    return { ...base, error: e instanceof AiError ? `${e.message} Showing a rule-based plan instead.` : "The AI step failed — showing a rule-based plan instead." };
  }
}
