// Turns src/lib/blog/src/*.md (front matter + Markdown) into src/lib/blog/posts.generated.ts.
// Run after editing or adding a post:  node scripts/build-blog.mjs
import fs from "fs";
import path from "path";
const dir = path.resolve("src/lib/blog/src");
const order = ["get-recommended-by-chatgpt-gemini-perplexity", "local-seo-checklist-small-business", "email-deliverability-spf-dkim-dmarc-guide", "whatsapp-business-api-guide-small-business", "30-day-marketing-plan-small-business"];
const parse = (d, f) => {
  const raw = fs.readFileSync(path.join(d, f), "utf8");
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${f}: missing front matter`);
  const meta = Object.fromEntries(m[1].split("\n").filter((l) => l.includes(":")).map((l) => { const i = l.indexOf(":"); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"(.*)"$/, "$1")]; }));
  return { meta, body: m[2].trim() };
};
const posts = fs.readdirSync(dir).filter((f) => f.endsWith(".md")).map((f) => {
  const raw = fs.readFileSync(path.join(dir, f), "utf8");
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${f}: missing front matter`);
  const meta = Object.fromEntries(m[1].split("\n").map((l) => { const i = l.indexOf(":"); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"(.*)"$/, "$1")]; }));
  for (const k of ["slug", "title", "description", "keywords", "category"]) if (!meta[k]) throw new Error(`${f}: missing ${k}`);
  return { ...meta, keywords: meta.keywords.split(",").map((s) => s.trim()), published: meta.published || "2026-09-30", updated: meta.updated || meta.published || "2026-09-30", body: m[2].trim() };
}).sort((a, b) => (order.indexOf(a.slug) + 1 || 99) - (order.indexOf(b.slug) + 1 || 99));
const out = `// Generated by scripts/build-blog.mjs from src/lib/blog/src/*.md — edit the .md files, then re-run the script.\nimport type { Post } from "./types";\n\nexport const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};\n`;
fs.writeFileSync("src/lib/blog/posts.generated.ts", out);
console.log(`Wrote ${posts.length} posts`);

// US local market pages: src/lib/local/src/*.md → src/lib/local/pages.generated.ts
const ldir = path.resolve("src/lib/local/src");
const locals = fs.existsSync(ldir) ? fs.readdirSync(ldir).filter((f) => f.endsWith(".md")).map((f) => {
  const { meta, body } = parse(ldir, f);
  for (const k of ["slug", "title", "description", "keywords", "county", "state", "stateCode", "metro", "population", "published"]) if (!meta[k]) throw new Error(`${f}: missing ${k}`);
  return { ...meta, keywords: meta.keywords.split(",").map((s) => s.trim()), updated: meta.updated || meta.published, body };
}).sort((a, b) => a.state.localeCompare(b.state) || a.county.localeCompare(b.county)) : [];
fs.writeFileSync("src/lib/local/pages.generated.ts", `// Generated by scripts/build-blog.mjs from src/lib/local/src/*.md — edit the .md files, then re-run the script.\nimport type { LocalPage } from "../blog/types";\n\nexport const LOCAL_PAGES: LocalPage[] = ${JSON.stringify(locals, null, 2)};\n`);
console.log(`Wrote ${locals.length} local pages`);
